### ISSUE TITLE
Create deployment yaml

### ISSUE THREAD

**Issue by rrati** [kubernetes-sigs/container-object-storage-interface-provisioner-sidecar#23]
Create deployment yamls that will deploy the sidecar and a driver that can be used to deploy just those components, or be part of a global deploy that would deploy all of object storage.

Other components of object storage have been using kustomize to do this, so this needs to fit into that scheme.

**Comment by NicolasT** [comment]
Would be cool if this would exist (potentially based on https://raw.githubusercontent.com/container-object-storage-interface/cosi-provisioner-sidecar/master/examples/object-storage-sidecar.yaml ?), after which https://github.com/kubernetes-sigs/container-object-storage-interface-controller/blob/master/deploy/fullstack/kustomization.yaml can be updated to have this repo's `kustomization` as `base` (and removing `provisioner/` in there), instead of the work-around at https://github.com/kubernetes-sigs/container-object-storage-interface-controller/blob/d79d353371a0a1e6246783733fd6b3043e591e83/deploy/fullstack/provisioner/kustomization.yaml#L11
